[
  {
    row: "A",
    col: 1,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 2,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 3,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 4,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 5,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 6,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 7,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 8,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 9,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 10,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 11,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "A",
    col: 12,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 1,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 2,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 3,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 4,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 5,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 6,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 7,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 8,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 9,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 10,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 11,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "B",
    col: 12,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 1,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 2,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 3,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 4,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 5,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 6,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 7,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 8,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 9,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 10,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 11,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "C",
    col: 12,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "D",
    col: 1,
    botA: 1745,
    spotTwo: 44,
    ricin: 50,
    spotFour: 39,
    pcH: 12994,
    spotSix: 34,
    seb: 58,
    spotEight: 29,
    pcL: 137
  },
  {
    row: "D",
    col: 2,
    botA: 1795,
    spotTwo: 31,
    ricin: 48,
    spotFour: 34,
    pcH: 12517,
    spotSix: 37,
    seb: 58,
    spotEight: 25,
    pcL: 48
  },
  {
    row: "D",
    col: 3,
    botA: 348,
    spotTwo: 35,
    ricin: 41,
    spotFour: 35,
    pcH: 9889,
    spotSix: 26,
    seb: 49,
    spotEight: 25,
    pcL: 421
  },
  {
    row: "D",
    col: 4,
    botA: 282,
    spotTwo: 25,
    ricin: 40,
    spotFour: 28,
    pcH: 8319,
    spotSix: 19,
    seb: 47,
    spotEight: 21,
    pcL: 35
  },
  {
    row: "D",
    col: 5,
    botA: 16475,
    spotTwo: 34,
    ricin: 51,
    spotFour: 55,
    pcH: 11420,
    spotSix: 21,
    seb: 81,
    spotEight: 26,
    pcL: 124
  },
  {
    row: "D",
    col: 6,
    botA: 2041,
    spotTwo: 29,
    ricin: 42,
    spotFour: 31,
    pcH: 8881,
    spotSix: 26,
    seb: 5352,
    spotEight: 19,
    pcL: 258
  },
  {
    row: "D",
    col: 7,
    botA: 2005,
    spotTwo: 28,
    ricin: 2412,
    spotFour: 26,
    pcH: 8929,
    spotSix: 24,
    seb: 46,
    spotEight: 18,
    pcL: 47
  },
  {
    row: "D",
    col: 8,
    botA: 5,
    spotTwo: -1,
    ricin: -2,
    spotFour: 2,
    pcH: -7,
    spotSix: -2,
    seb: 2,
    spotEight: -10,
    pcL: 2
  },
  {
    row: "D",
    col: 9,
    botA: -2,
    spotTwo: -7,
    ricin: 3,
    spotFour: -2,
    pcH: -2,
    spotSix: 0,
    seb: 1,
    spotEight: -9,
    pcL: 14
  },
  {
    row: "D",
    col: 10,
    botA: -3,
    spotTwo: -6,
    ricin: 1,
    spotFour: -1,
    pcH: -3,
    spotSix: 4,
    seb: -10,
    spotEight: -1,
    pcL: -1
  },
  {
    row: "D",
    col: 11,
    botA: 1,
    spotTwo: 0,
    ricin: 3,
    spotFour: -3,
    pcH: 2,
    spotSix: -1,
    seb: -13,
    spotEight: -5,
    pcL: 3
  },
  {
    row: "D",
    col: 12,
    botA: 1,
    spotTwo: -1,
    ricin: -6,
    spotFour: -5,
    pcH: 3,
    spotSix: 0,
    seb: -5,
    spotEight: -5,
    pcL: 0
  },
  {
    row: "E",
    col: 1,
    botA: 60,
    spotTwo: 34,
    ricin: 41,
    spotFour: 29,
    pcH: 13051,
    spotSix: 30,
    seb: 46,
    spotEight: 27,
    pcL: 48
  },
  {
    row: "E",
    col: 2,
    botA: 75,
    spotTwo: 34,
    ricin: 48,
    spotFour: 40,
    pcH: 12995,
    spotSix: 32,
    seb: 51,
    spotEight: 31,
    pcL: 52
  },
  {
    row: "E",
    col: 3,
    botA: 48,
    spotTwo: 33,
    ricin: 43,
    spotFour: 34,
    pcH: 13346,
    spotSix: 24,
    seb: 53,
    spotEight: 31,
    pcL: 49
  },
  {
    row: "E",
    col: 4,
    botA: 51,
    spotTwo: 27,
    ricin: 49,
    spotFour: 45,
    pcH: 12764,
    spotSix: 31,
    seb: 51,
    spotEight: 35,
    pcL: 53
  },
  {
    row: "E",
    col: 5,
    botA: 1,
    spotTwo: -2,
    ricin: 3,
    spotFour: -1,
    pcH: -2,
    spotSix: 10,
    seb: 1,
    spotEight: -13,
    pcL: 13
  },
  {
    row: "E",
    col: 6,
    botA: 0,
    spotTwo: -2,
    ricin: -3,
    spotFour: -9,
    pcH: -5,
    spotSix: -12,
    seb: 5,
    spotEight: -4,
    pcL: 4
  },
  {
    row: "E",
    col: 7,
    botA: 2,
    spotTwo: -2,
    ricin: 1,
    spotFour: -6,
    pcH: 2,
    spotSix: 7,
    seb: -5,
    spotEight: -6,
    pcL: 5
  },
  {
    row: "E",
    col: 8,
    botA: 3,
    spotTwo: -1,
    ricin: -3,
    spotFour: -5,
    pcH: -8,
    spotSix: 3,
    seb: 4,
    spotEight: -8,
    pcL: 12
  },
  {
    row: "E",
    col: 9,
    botA: 3,
    spotTwo: -5,
    ricin: 0,
    spotFour: -3,
    pcH: 0,
    spotSix: 1,
    seb: 2,
    spotEight: -2,
    pcL: 0
  },
  {
    row: "E",
    col: 10,
    botA: 2,
    spotTwo: -6,
    ricin: -2,
    spotFour: 5,
    pcH: 2,
    spotSix: 3,
    seb: -3,
    spotEight: -1,
    pcL: 0
  },
  {
    row: "E",
    col: 11,
    botA: 40,
    spotTwo: 27,
    ricin: 40,
    spotFour: 28,
    pcH: 12683,
    spotSix: 25,
    seb: 53,
    spotEight: 25,
    pcL: 47
  },
  {
    row: "E",
    col: 12,
    botA: 42,
    spotTwo: 37,
    ricin: 44,
    spotFour: 33,
    pcH: 13065,
    spotSix: 42,
    seb: 49,
    spotEight: 28,
    pcL: 42
  },
  {
    row: "F",
    col: 1,
    botA: 18993,
    spotTwo: 62,
    ricin: 62,
    spotFour: 77,
    pcH: 13214,
    spotSix: 40,
    seb: 80,
    spotEight: 44,
    pcL: 59
  },
  {
    row: "F",
    col: 2,
    botA: 53,
    spotTwo: 37,
    ricin: 38,
    spotFour: 40,
    pcH: 13531,
    spotSix: 30,
    seb: 6417,
    spotEight: 34,
    pcL: 51
  },
  {
    row: "F",
    col: 3,
    botA: 53,
    spotTwo: 40,
    ricin: 2996,
    spotFour: 49,
    pcH: 13991,
    spotSix: 21,
    seb: 60,
    spotEight: 31,
    pcL: 55
  },
  {
    row: "F",
    col: 4,
    botA: 14424,
    spotTwo: 30,
    ricin: 45,
    spotFour: 56,
    pcH: 6589,
    spotSix: 35,
    seb: 79,
    spotEight: 27,
    pcL: 63
  },
  {
    row: "F",
    col: 5,
    botA: 46,
    spotTwo: 32,
    ricin: 53,
    spotFour: 38,
    pcH: 12129,
    spotSix: 34,
    seb: 6645,
    spotEight: 43,
    pcL: 56
  },
  {
    row: "F",
    col: 6,
    botA: 50,
    spotTwo: 40,
    ricin: 3314,
    spotFour: 43,
    pcH: 12544,
    spotSix: 28,
    seb: 58,
    spotEight: 33,
    pcL: 48
  },
  {
    row: "F",
    col: 7,
    botA: 44,
    spotTwo: 28,
    ricin: 45,
    spotFour: 42,
    pcH: 12882,
    spotSix: 29,
    seb: 58,
    spotEight: 25,
    pcL: 50
  },
  {
    row: "F",
    col: 8,
    botA: 42,
    spotTwo: 34,
    ricin: 44,
    spotFour: 25,
    pcH: 11827,
    spotSix: 38,
    seb: 49,
    spotEight: 27,
    pcL: 50
  },
  {
    row: "F",
    col: 9,
    botA: 49,
    spotTwo: 28,
    ricin: 47,
    spotFour: 27,
    pcH: 12138,
    spotSix: 34,
    seb: 54,
    spotEight: 36,
    pcL: 48
  },
  {
    row: "F",
    col: 10,
    botA: 35,
    spotTwo: 23,
    ricin: 50,
    spotFour: 23,
    pcH: 9613,
    spotSix: 27,
    seb: 46,
    spotEight: 23,
    pcL: 46
  },
  {
    row: "F",
    col: 11,
    botA: 57,
    spotTwo: 39,
    ricin: 52,
    spotFour: 42,
    pcH: 11932,
    spotSix: 35,
    seb: 59,
    spotEight: 34,
    pcL: 49
  },
  {
    row: "F",
    col: 12,
    botA: 4,
    spotTwo: -2,
    ricin: 3,
    spotFour: -2,
    pcH: -5,
    spotSix: 11,
    seb: 4,
    spotEight: -4,
    pcL: 15
  },
  {
    row: "G",
    col: 1,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 2,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 3,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 4,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 5,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 6,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 7,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 8,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 9,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 10,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 11,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "G",
    col: 12,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 1,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 2,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 3,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 4,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 5,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 6,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 7,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 8,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 9,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 10,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 11,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  },
  {
    row: "H",
    col: 12,
    botA: null,
    spotTwo: null,
    ricin: null,
    spotFour: null,
    pcH: null,
    spotSix: null,
    seb: null,
    spotEight: null,
    pcL: null
  }
];
